// Automatically generated by the bundler tool from d:\Program Files\Microsoft Xbox SDK\Samples\Xbox\ReferenceUI\VirtualKeyboard\font12.rdf

#define font12_NUM_RESOURCES 2UL

#define font12_Font_OFFSET 0UL
#define font12_FontData_OFFSET 20UL
