// Automatically generated by the bundler tool from d:\Program Files\Microsoft Xbox SDK\Samples\Xbox\ReferenceUI\VirtualKeyboard\font18.rdf

#define font18_NUM_RESOURCES 2UL

#define font18_Font_OFFSET 0UL
#define font18_FontData_OFFSET 20UL
