// Automatically generated by the bundler tool from d:\Program Files\Microsoft Xbox SDK\Samples\Xbox\ReferenceUI\VirtualKeyboard\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_KeyboardKey_OFFSET 0UL
