// Automatically generated by the bundler tool from d:\Program Files\Microsoft Xbox SDK\Samples\Xbox\ReferenceUI\VirtualKeyboard\xboxdings_24.rdf

#define xboxdings_24_NUM_RESOURCES 2UL

#define xboxdings_24_Font_OFFSET 0UL
#define xboxdings_24_FontData_OFFSET 20UL
