/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* use GNU internationalization */
#undef USE_I18N

/* use setlocale() function */
#define USE_SETLOCALE 0

/* Runtime CPU detection */
#define RUNTIME_CPUDETECT 1
#define USE_QTX_CODECS 1
/* "restrict" keyword */
#define restrict __restrict
#define USE_STREAM_CACHE 1
#define PREFIX 
#define NEW_CONFIG 1
/* define this to use simple idct with patched libavcodec */
#define SIMPLE_IDCT 1
#define _LARGEFILE_SOURCE 1
#define USE_OSD 1 
#define USE_SUB 1 
#undef HAVE_XMMS 
/* enable/disable SIGHANDLER */

/* Toggles debugging informations */
#undef MP_DEBUG
#define HAVE_MATROSKA 1
/* Indicates that Ogle's libdvdread is available for DVD playback */
#define USE_DVDREAD 1
#define HAVE_OGGTHEORA 1
/* Indicates that dvdread is from libmpdvdkit */
#define USE_MPDVDKIT 2

/* Additional options for libmpdvdkit*/
#undef DVD_STRUCT_IN_DVD_H
#undef DVD_STRUCT_IN_LINUX_CDROM_H
#undef DVD_STRUCT_IN_SYS_CDIO_H
#undef DVD_STRUCT_IN_SYS_DVDIO_H
#undef DVD_STRUCT_IN_BSDI_DVDIOCTL_DVD_H



#undef SOLARIS_USCSI
#undef HPUX_SCTL
#define HAVE_STDDEF_H 1

/* Common data directory (for fonts, etc) */
#define DATADIR 
#define CONFDIR 
#define LIBDIR 

/* Define this to compile stream-caching support, it can be enabled via
   -cache <kilobytes> */

/* Define to include support for XviD/Divx4Linux/OpenDivx */
#undef USE_DIVX

/* Define to use the new XviD/DivX4Linux library instead of open source OpenDivX */
/* You have to change DECORE_LIBS in config.mak, too! */
#undef NEW_DECORE

/* Define if you are using DivX5Linux Decore library */
#define DECORE_DIVX5 1

/* Define if you are using XviD library */
#define HAVE_XVID 1

/* Define if you have divx4.h in place of decore.h */
#define HAVE_DIVX4_H 1

/* Define to include support for libdv-0.9.5 */
#undef HAVE_LIBDV095 

/* If build mencoder */
#define HAVE_MENCODER

/* Indicates if XviD/Divx4linux encore is available
   Note: for mencoder */
#undef HAVE_DIVX4ENCORE

/* Indicates if libmp3lame is available
   Note: for mencoder */
#undef HAVE_MP3LAME

/* Define libmp1e for realtime mpeg encoding (for DXR3 and DVB cards) */
#undef USE_MP1E

/* Define this to enable avg. byte/sec-based AVI sync method by default:
   (use -bps or -nobps commandline option for run-time method selection)
   -bps gives better sync for vbr mp3 audio, it is now default */
#define AVI_SYNC_BPS 1

/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
//#define USE_FAKE_MONO 1

/* Undefine this if your sound card driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
/* # define HAVE_AUDIO_SELECT 1*/

/* define this to use iconv(3) function to codepage conversions */
#undef USE_ICONV

/* define this to use RTC (/dev/rtc) for video timers (LINUX only) */
#undef HAVE_RTC

/* set up max. outburst. use 65536 for ALSA 0.5, for others 16384 is enough */
#define MAX_OUTBURST 65536

/* set up audio OUTBURST. Do not change this! */
#define OUTBURST 512


/* Define this if your system has the header file for the OSS sound interface
 * in /usr/include */
#undef HAVE_SOUNDCARD_H

/* Define this if your system has the sysinfo header */
#undef HAVE_SYS_SYSINFO_H

/* Define this if your system uses ftello() for off_t seeking */

#undef HAVE_FTELLO
#ifndef HAVE_FTELLO
# define ftello(a) ftell(a)
#endif

/* Define this if your system has the "malloc.h" header file */
#define HAVE_MALLOC_H 1

/* memalign is mapped to malloc if unsupported */
#undef HAVE_MEMALIGN
#ifndef HAVE_MEMALIGN
# define memalign(a,b) malloc(b)
#endif

/* Define this if your system has the "alloca.h" header file */
#define HAVE_ALLOCA_H 1

/* Define this if your system has the "sys/mman.h" header file */

/* Define this if you have the elf dynamic linker -ldl library */
#define HAVE_LIBDL 1

/* Define this if you have the kstat kernel statistics library */
#undef HAVE_LIBKSTAT

/* Define this if you have zlib */
/* # define HAVE_ZLIB 1*/

/* Define this if you have shm support */
#undef HAVE_SHM

/* Define this if your system has strsep */
#undef  HAVE_STRSEP 

/* Define this if your system has vsscanf */
#define HAVE_VSSCANF 1

/* LIRC (remote control, see www.lirc.org) support: */
#undef HAVE_LIRC

/* DeCSS support using libcss */
#undef HAVE_LIBCSS

/* DVD navigation support using libdvdnav */
#define USE_DVDNAV 1


/* Define this to enable MPEG 1/2 image postprocessing (requires a FAST CPU!) */
#define MPEG12_POSTPROC 1

/* Define this to enable image postprocessing in libavcodec (requires a FAST CPU!) */
#define FF_POSTPROCESS 1

/* Define to include support for OpenDivx postprocessing */
#undef HAVE_ODIVX_POSTPROCESS

/* Win32 DLL support */
#define USE_WIN32DLL 1

/* DirectShow support */
#define USE_DIRECTSHOW 1

/* ffmpeg's libavcodec support (requires libavcodec source) */
#define USE_LIBAVCODEC 1
#undef USE_LIBAVCODEC_SO

/* Use libavcodec's decoders */
#define CONFIG_DECODERS 1
/* Use libavcodec's encoders */

/* Use codec libs included in mplayer CVS / source dist: */
#define USE_MP3LIB 1
#define USE_LIBA52 1
#define USE_LIBMPEG2 1

/* Use the SVQ1 decoder in libmpcodecs - we don't want/need it with libavcodec */
#ifndef USE_LIBAVCODEC
#define USE_SVQ1 1
#endif

/* Use libfame encoder filter */
#undef USE_LIBFAME 

/* XAnim DLL support */
#undef USE_XANIM
/* Default search path */
#undef XACODEC_PATH

/* RealPlayer DLL support */
#define USE_REALCODECS 1

/* Default search path */
#define REALCODEC_PATH "Q:\\dll"

/* LIVE.COM Streaming Media library support */
#undef STREAMING_LIVE_DOT_COM

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#define USE_FASTMEMCPY 1

/* Use unrarlib for Vobsubs */
#define USE_UNRARLIB 1

/* gui support, please do not edit this option */
#undef HAVE_NEW_GUI

/* Audio output drivers */
#undef HAVE_ALSA5
#undef HAVE_ALSA9

#undef HAVE_SYS_ASOUNDLIB_H
#undef HAVE_ALSA_ASOUNDLIB_H
#undef USE_SUN_AUDIO
#undef USE_SGI_AUDIO
#define HAVE_WIN32WAVEOUT 1
#undef HAVE_NAS

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#undef FAST_OSD
#undef FAST_OSD_TABLE

/* Enable TV Interface support */

/* Enable Video 4 Linux TV interface support */
#undef HAVE_TV_V4L

/* Enable *BSD BrookTree TV interface support */
#undef HAVE_TV_BSDBT848

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#undef WORDS_BIGENDIAN

#define ARCH_X86 1

/* Define this for Cygwin build for win32 */


/* Define this to any prefered value from 386 up to infinity with step 100 */
#define __CPU__ 686

#define MP_WORDSIZE 32

#undef TARGET_LINUX

#undef HAVE_VCD

#if defined (_XBOX)

#define DEFAULT_CDROM_DEVICE	"\\Device\\Cdrom0"

#define DEFAULT_DVD_DEVICE		"\\Device\\Cdrom0"

#else

#define DEFAULT_CDROM_DEVICE    "cdrom:"

#define DEFAULT_DVD_DEVICE	"cdromcdrom:"

#endif



/*----------------------------------------------------------------------------
**
** NOTE: Instead of modifying these definitions here, use the
**       --enable/--disable options of the ./configure script!
**       See ./configure --help for details.
**
*---------------------------------------------------------------------------*/

/* C99 lrintf function available */
#undef HAVE_LRINTF

/* nanosleep support */
#undef HAVE_NANOSLEEP

/* termcap flag for getch2.c */

/* termios flag for getch2.c */
#undef HAVE_TERMIOS_H

/* enable PNG support */
#undef HAVE_PNG

/* enable JPEG support */
#undef HAVE_JPEG

/* enable GIF support */
#undef HAVE_GIF
#undef HAVE_GIF_4

/* enable FreeType support */
#undef HAVE_FREETYPE 

/* liblzo support */
#undef USE_LIBLZO

/* libmad support */
#define USE_LIBMAD 1

/* enable OggVorbis support */
#define HAVE_OGGVORBIS 1

/* enable FAAD (AAC) support */
#define HAVE_FAAD 1

/* enable streaming */
#define STREAMING 1

/* define this to use inet_aton() instead of inet_pton() */
#define USE_ATON 1

/* enables / disables cdparanoia support */
#define HAVE_CDDA 1
/* enables / disables vidix usage */
#undef CONFIG_VIDIX

/* enables / disables new input joystick support */
#undef HAVE_JOYSTICK

/* Extension defines */
#undef HAVE_3DNOW	// only define if you have 3DNOW (AMD k6-2, AMD Athlon, iDT WinChip, etc.)
#undef HAVE_3DNOWEX	// only define if you have 3DNOWEX (AMD Athlon, etc.)
#define HAVE_MMX 1	// only define if you have MMX (newer x86 chips, not P54C/PPro)
#define HAVE_MMX2 1	// only define if you have MMX2 (Athlon/PIII/4/CelII)
#define HAVE_SSE 1	// only define if you have SSE (Intel Pentium III/4 or Celeron II)
#undef HAVE_SSE2	// only define if you have SSE2 (Intel Pentium 4)

#ifdef HAVE_MMX
#define USE_MMX_IDCT 1
#endif

#undef HAVE_MLIB  // Sun mediaLib, available only on solaris

/* libmpeg2 uses a different feature test macro for mediaLib */
#ifdef HAVE_MLIB
#define LIBMPEG2_MLIB 1
#endif

/* libvo options */
#define SCREEN_SIZE_X 1
#define SCREEN_SIZE_Y 1
#undef HAVE_X11
#undef HAVE_XV
#undef HAVE_XF86VM
#undef HAVE_XINERAMA
#undef HAVE_GL
#undef HAVE_DGA
#undef HAVE_DGA2
#undef HAVE_SDL
/* defined for SDLlib with keyrepeat bugs (before 1.2.1) */

#define HAVE_DIRECTX 1
#undef HAVE_GGI
#undef HAVE_3DFX
#undef HAVE_TDFXFB
#undef HAVE_DIRECTFB

#undef HAVE_ZR
#undef HAVE_BL
#undef HAVE_MGA
#undef HAVE_XMGA

#undef HAVE_FBDEV
#undef USE_CONVERT2FB
#undef HAVE_DXR2
#undef HAVE_DXR3
#undef HAVE_DVB
#undef HAVE_SVGALIB
#undef HAVE_VESA
#undef HAVE_XDPMS
#undef HAVE_AA

/* used by GUI: */


#if defined(HAVE_GL) || defined(HAVE_X11) || defined(HAVE_XV)
#define X11_FULLSCREEN 1
#endif

